name: bybit_v5
description: Dart package to communicate with Bybit API V5.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  http: ^1.2.1
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
